# .pre-commit-config.yaml
repos:
  # Ruff for formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7 # Use the latest stable version of Ruff
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Optional: automatically fix issues and exit with non-zero on fix
      - id: ruff-format

  # Mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1 # Use the latest stable version of Mypy
    hooks:
      - id: mypy
        args: [--ignore-missing-imports] # Optional: ignore missing imports

  # Pytest for running tests
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false # Run pytest on all files, not just changed ones