[project]
name = "bandit-exploration"
version = "0.1.0"
description = "My personal reimplementation of various bandit algorithms."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvxpy>=1.7.1",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "tqdm>=4.67.1",
]
